services:
  mongodb:
    image: mongo:7
    container_name: naniiicu-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-naniiicu}
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: naniiicu-backend
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3002
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:8084,http://localhost:8082}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE:-naniiicu}
      MONGO_AUTH_SOURCE: admin
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-100}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3002/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    build:
      context: ./naniiicu-app
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3002}
    container_name: naniiicu-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8084:80"

volumes:
  mongodb-data:
    driver: local